version: 3

tasks:
  install:helm:add-repo:
    cmds:
    - helm repo add deepfence https://deepfence-helm-charts.s3.amazonaws.com/threatmapper
    status:
    - helm repo list | grep deepfence

  install:helm:
    deps:
    - install:helm:add-repo
    cmds:
    - helm upgrade --install deepfence-console deepfence/deepfence-console -n threatmapper --create-namespace

  uninstall:helm:
    cmds:
    - helm uninstall -n 

# # Optionally, install the Deepfence Router service and wait for the platform to deploy a load balancer
# helm install deepfence-router deepfence/deepfence-router
# kubectl get --namespace default svc -w deepfence-router