version: '3'

includes:
  demo:microshift: .taskfiles/demo/microshift.yaml  
  charts: .taskfiles/charts.yaml
  flux: .taskfiles/flux.yaml
  tools:syft: .taskfiles/tools/syft.yaml
  tools:grype: .taskfiles/tools/grype.yaml
  git: ../lib-system-manager/.taskfiles/git.yaml
  ansible: .taskfiles/ansible.yaml
  python: .taskfiles/python.yaml
  apps: .taskfiles/apps.yaml
  apps:teleport: .taskfiles/apps/teleport.yaml
  local-apps: .taskfiles/local-apps.yaml
  istio: .taskfiles/istio.yaml
  monitoring: .taskfiles/monitoring.yaml

vars:
  STATUS_FILES_PATH: .taskfiles/statusfiles
  USER_STATUS_FILES_PATH: ~/.statusfiles

tasks:
  default:
    cmds:
    - task -l
    silent: true
