version: '3'

includes:
  demo:microshift: .taskfiles/demo/microshift.yaml  
  charts: .taskfiles/charts.yaml
  flux: .taskfiles/flux.yaml
  tools:syft: .taskfiles/tools/syft.yaml
  tools:grype: .taskfiles/tools/grype.yaml
  git: ../lib-system-manager/.taskfiles/git.yaml
  ansible: .taskfiles/ansible.yaml
  python: .taskfiles/python.yaml
  apps: .taskfiles/apps.yaml
  local-apps: .taskfiles/local-apps.yaml
  istio: .taskfiles/istio.yaml
  monitoring: .taskfiles/monitoring.yaml
  tools:mizu: tools/mizu/Taskfile.yaml
  k8s-apps:skydive: 
    taskfile: k8s-apps/skydive/Taskfile.yaml
    dir: k8s-apps/skydive
  k8s-dashboards:weave-scope:
    taskfile: k8s-dashboards/weave-scope/Taskfile.yaml
    dir: k8s-dashboards/weave-scope
  tools:octant:
    taskfile: tools/octant/Taskfile.yaml
    dir: tools/octant
vars:
  STATUS_FILES_PATH: .taskfiles/statusfiles
  USER_STATUS_FILES_PATH: ~/.statusfiles

tasks:
  default:
    cmds:
    - task -l
    silent: true
