version: '3'

tasks:
  add-helm-repo:
    cmds:
    - helm repo add teleport https://charts.releases.teleport.dev
    status:
    - helm repo list | grep teleport
    preconditions:
    - helm

  install:helm:
    deps:
    - add-helm-repo
    cmds:
    - >
      helm upgrade --install teleport-cluster teleport/teleport-cluster
      --set clusterName=teleport.127.0.0.1.nip.io
    - sleep 5s && kubectl wait pod -l app=teleport-cluster --for condition=Ready --timeout 180s

  show-helm-values:
    deps:
    - add-helm-repo
    cmds:
    - helm show values teleport/teleport-cluster

  add-user:
    deps:
    - install:helm
    env:
      POD: 
        sh: kubectl get pod -l app=teleport-cluster -o jsonpath='{.items[0].metadata.name}'
    cmds:
    - kubectl exec -i ${POD?} -- tctl create -f < config/teleport-role.yaml
    - kubectl exec -ti ${POD?} -- tctl  users add krzwiatrzyk --logins=krzwiatrzyk,root --roles=member,access,editor
    
  login-to-kubernetes:
    cmds:
    - tsh --insecure login --proxy=teleport.127.0.0.1.nip.io:443 --auth=local --user=krzwiatrzyk teleport.127.0.0.1.nip.io
    - tsh --insecure kube login teleport.127.0.0.1.nip.io

  install-agent-on-the-host:
  - curl -O https://get.gravitational.com/teleport-v9.0.0-linux-amd64-bin.tar.gz
  - tar -xzf teleport-v9.0.0-linux-amd64-bin.tar.gz
  - rm teleport-v9.0.0-linux-amd64-bin.tar.gz
  - cd teleport && sudo ./install
  - rm -rf teleport

  join-server:
    env:
      POD: 
        sh: kubectl get pod -l app=teleport-cluster -o jsonpath='{.items[0].metadata.name}'
    cmds:
      - >
        kubectl exec -i ${POD?} -- tctl tokens add --type=node | grep -oP '(?<=token:\s).*' | tr -d "." > /tmp/token.txt
      #- sudo bash -c "$(curl --insecure -fsSL https://teleport.127.0.0.1.nip.io/scripts/d31f940acceb74d73f04d050f6012f7f/install-node.sh)"
      - >
        sudo teleport start 
        --insecure
        --roles=node 
        --token=/tmp/token.txt 
        --auth-server=teleport.127.0.0.1.nip.io:443 &

  clear:
  - sudo rm -rf /var/lib/teleport
  - sudo rm -f /etc/teleport.yaml
  - sudo pkill -f teleport

