version: 3

tasks:
  install:cli:
  - |
    # Download the binary
    curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.3.3/argo-linux-amd64.gz

    # Unzip
    gunzip argo-linux-amd64.gz

    # Make binary executable
    chmod +x argo-linux-amd64

    # Move binary to path
    sudo mv ./argo-linux-amd64 /usr/local/bin/argo

  install:helm:
  - helm upgrade --install argo-workflows argo/argo-workflows -n argo-workflows --create-namespace --values values.yaml


  install:ingress-route:
  - kubectl apply -n argo-workflows -f manifests/ingress-route/ingress-route.yaml

  submit:workflows:cowsay:
  - argo submit manifests/workflows/cowsay.yaml 

  submit:workflows:dag:
  - argo submit manifests/workflows/dag.yaml