apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
  - port: traefik
    path: /metrics