apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testkube
  namespace: testkube
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`testkube.127.0.0.1.nip.io`)
    kind: Rule
    services:   
    - kind: Service 
      name: testkube-dashboard
      port: 80